/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import interfaces.UsuarioServiceImp;
import javax.swing.JOptionPane;
import models.Usuario;
import services.UsuarioService;

/**
 *
 * @author pausa
 */
public class frmSignIn extends javax.swing.JPanel {

    private final UsuarioServiceImp user = new UsuarioService();
    private String nombre;
    private String apellido;
    private String email;
    private String contrasenia;
    /**
     * Creates new form frmSignIn
     */
    public frmSignIn() {
        initComponents();
        
        this.nombre = nombreField2.getText();
        this.apellido = apellidoField2.getText();
        this.email = emailField2.getText();
        this.contrasenia = new String(jPasswordField4.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        nombreLabel2 = new javax.swing.JLabel();
        nombreField2 = new javax.swing.JTextField();
        apellidoLabel2 = new javax.swing.JLabel();
        apellidoField2 = new javax.swing.JTextField();
        emailLabel2 = new javax.swing.JLabel();
        emailField2 = new javax.swing.JTextField();
        pwLabel2 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(74, 94, 236));
        jPanel3.setForeground(new java.awt.Color(74, 94, 236));
        jPanel3.setAutoscrolls(true);

        nombreLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombreLabel2.setText("Nombre");

        nombreField2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombreField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreField2ActionPerformed(evt);
            }
        });

        apellidoLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        apellidoLabel2.setText("Apellido");

        apellidoField2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        emailLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        emailLabel2.setText("Correo");

        emailField2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        pwLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pwLabel2.setText("Contraseña");

        jPasswordField4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jButton3.setText("Registrarse");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(emailField2)
                    .addComponent(emailLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apellidoField2)
                            .addComponent(apellidoLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreField2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(nombreLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPasswordField4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(nombreLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidoLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidoField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
        nombre = nombreField2.getText();
        apellido = apellidoField2.getText();
        email = emailField2.getText();
        contrasenia = new String(jPasswordField4.getPassword());

        // Validaciones de los campos
        if (!nombre.matches("^[a-zA-Z]{1,50}$")) {
            JOptionPane.showMessageDialog(this, "El nombre debe contener solo letras y tener menos de 50 caracteres.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!apellido.matches("^[a-zA-Z]{1,50}$")) {
            JOptionPane.showMessageDialog(this, "El apellido debe contener solo letras y tener menos de 50 caracteres.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.matches("^[\\w._%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}$") || email.length() > 100) {
            JOptionPane.showMessageDialog(this, "El email debe tener un formato válido y no superar los 100 caracteres.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (contrasenia.length() > 60) {
            JOptionPane.showMessageDialog(this, "La contraseña no puede superar los 60 caracteres.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Registro del usuario
        user.Registrar(new Usuario(nombre, apellido, email, contrasenia));
        JOptionPane.showMessageDialog(null, "Usuario registrado con éxito");
    }//GEN-LAST:event_jButton3MouseClicked

    private void nombreField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoField;
    private javax.swing.JTextField apellidoField1;
    private javax.swing.JTextField apellidoField2;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JLabel apellidoLabel1;
    private javax.swing.JLabel apellidoLabel2;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emailField1;
    private javax.swing.JTextField emailField2;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField nombreField1;
    private javax.swing.JTextField nombreField2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JLabel nombreLabel2;
    private javax.swing.JLabel pwLabel;
    private javax.swing.JLabel pwLabel1;
    private javax.swing.JLabel pwLabel2;
    // End of variables declaration//GEN-END:variables
}
